// <auto-generated />
using System;
using Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20251127230858_CreatedAtProduct")]
    partial class CreatedAtProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Мышка игровая",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Мышка",
                            Price = 590m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Механическая",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Клавиатура",
                            Price = 1290m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Беспроводные",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Наушники",
                            Price = 1990m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Oled",
                            IsAvailable = true,
                            IsDeleted = false,
                            Name = "Монитор",
                            Price = 290900m,
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
